# Generated by Django 4.2.1 on 2023-05-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_band_like_new"),
    ]

    operations = [
        migrations.RemoveField(model_name="band", name="like_new",),
    ]
